"""second migration

Revision ID: 103fc4afafd0
Revises: 54eb1907476e
Create Date: 2023-11-08 18:58:52.635273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103fc4afafd0'
down_revision = '54eb1907476e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingroom', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetingroom', 'description')
    # ### end Alembic commands ###
